/*----- PROTECTED REGION ID(Itest2811ControllerClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        Itest2811ControllerClass.cpp
//
// description : C++ source for the Itest2811ControllerClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     BILT multi channel power supply.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Itest2811ControllerClass.h>

/*----- PROTECTED REGION END -----*/

//-------------------------------------------------------------------
/**
 *	Create Itest2811ControllerClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Itest2811Controller_class(const char *name) {
		return Itest2811Controller_ns::Itest2811ControllerClass::init(name);
	}
}


namespace Itest2811Controller_ns
{


//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
Itest2811ControllerClass *Itest2811ControllerClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::Itest2811ControllerClass(string &s)
 * description : 	constructor for the Itest2811ControllerClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
Itest2811ControllerClass::Itest2811ControllerClass(string &s):DeviceClass(s)
{
	cout2 << "Entering Itest2811ControllerClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(Itest2811Controller::Class::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::constructor

	cout2 << "Leaving Itest2811ControllerClass constructor" << endl;
}


//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::~Itest2811ControllerClass()
 * description : 	destructor for the Itest2811ControllerClass
 */
//--------------------------------------------------------
Itest2811ControllerClass::~Itest2811ControllerClass()
{
	/*----- PROTECTED REGION ID(Itest2811Controller::Class::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
Itest2811ControllerClass *Itest2811ControllerClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new Itest2811ControllerClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
Itest2811ControllerClass *Itest2811ControllerClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}




//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		OnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OnClass::execute(): arrived" << endl;

	
	((static_cast<Itest2811Controller *>(device))->on());
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		OffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OffClass::execute(): arrived" << endl;

	
	((static_cast<Itest2811Controller *>(device))->off());
	return new CORBA::Any();
}
//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;

	
	((static_cast<Itest2811Controller *>(device))->reset());
	return new CORBA::Any();
}




//===================================================================
//	Properties management
//===================================================================

//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::get_class_property
 * description : 	Get the class property for specified name.
 *
 * @param	name  The property name
 */
//--------------------------------------------------------
Tango::DbDatum Itest2811ControllerClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::get_default_device_property()()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum Itest2811ControllerClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::get_default_class_property()()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum Itest2811ControllerClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::get_class_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void Itest2811ControllerClass::get_class_property()
{
}


//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *	              For each property, add to wizard property name and description.
 *	              If default value has been set, add it to wizard property and.
 *	              store it in a DbDatum.
 */
//--------------------------------------------------------
void Itest2811ControllerClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;
	
	//	Set Default Class Properties

	//	Set Default Device Properties

	prop_name = "IPAddress";
	prop_desc = "IP Address of BILT controller.  Each controller includes several magnets and  each magnet includes 3 power supplies,  for corrections in the X, Y and Z planes.";
	prop_def  = "0.0.0.0\n";
	vect_data.clear();
	vect_data.push_back("0.0.0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "MagnetNumber";
	prop_desc = "Magnet number from 1 to 48";
	prop_def  = "0\n";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "UpdatePeriod";
	prop_desc = "The update period  for the data reading from the power supply in milli seconds.";
	prop_def  = "1000\n";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Channels";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}


//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void Itest2811ControllerClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("BILT multi channel power supply");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("By this device server for slow  or human control.");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename("Itest2811Controller");
	filename += "Class.cpp";
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_4Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}




//===================================================================
//	Factory methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::device_factory
 * description : 	Create the device object(s)
 *                  and store them in the device list
 *
 * @param	*devlist_ptr	The device name list
 */
//--------------------------------------------------------
void Itest2811ControllerClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	/*----- PROTECTED REGION ID(Itest2811Controller::Class::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Itest2811Controller(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Itest2811Controller *dev = static_cast<Itest2811Controller *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(Itest2811Controller::Class::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::device_factory_after

	
}


//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *	              and store them in the attribute list
 */
//--------------------------------------------------------
void Itest2811ControllerClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(Itest2811Controller::Class::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::attribute_factory_before

	//	Attribute : Currents
	CurrentsAttrib	*currents = new CurrentsAttrib();
	Tango::UserDefaultAttrProp	currents_prop;
	currents_prop.set_description("The measured currents of the three poles.");
	currents_prop.set_label("Currents");
	currents_prop.set_unit("A");
	//	standard_unit	not set for	Currents
	//	display_unit	not set for	Currents
	currents_prop.set_format("%6.4f");
	currents_prop.set_max_value("1.8");
	currents_prop.set_min_value("-1.8");
	currents_prop.set_max_alarm("1.5");
	currents_prop.set_min_alarm("-1.5");
	//	max_warning	not set for	Currents
	//	min_warning	not set for	Currents
	//	delta_t	not set for	Currents
	//	delta_val	not set for	Currents

	currents->set_default_properties(currents_prop);
	currents->set_polling_period(0);
	currents->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Currents does not fire change event
	//	Currents does not fire archive event
	//	Currents does not fire data_ready event

	att_list.push_back(currents);
	
	//	Attribute : Voltages
	VoltagesAttrib	*voltages = new VoltagesAttrib();
	Tango::UserDefaultAttrProp	voltages_prop;
	voltages_prop.set_description("The measured voltages of the three poles.");
	voltages_prop.set_label("Voltages");
	voltages_prop.set_unit("V");
	//	standard_unit	not set for	Voltages
	//	display_unit	not set for	Voltages
	voltages_prop.set_format("%6.4");
	//	max_value	not set for	Voltages
	//	min_value	not set for	Voltages
	//	max_alarm	not set for	Voltages
	//	min_alarm	not set for	Voltages
	//	max_warning	not set for	Voltages
	//	min_warning	not set for	Voltages
	//	delta_t	not set for	Voltages
	//	delta_val	not set for	Voltages

	voltages->set_default_properties(voltages_prop);
	voltages->set_polling_period(0);
	voltages->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Voltages does not fire change event
	//	Voltages does not fire archive event
	//	Voltages does not fire data_ready event

	att_list.push_back(voltages);
	
	//	Attribute : Impedances
	ImpedancesAttrib	*impedances = new ImpedancesAttrib();
	Tango::UserDefaultAttrProp	impedances_prop;
	impedances_prop.set_description("Calculated impedances for the three poles.");
	impedances_prop.set_label("Impedances");
	impedances_prop.set_unit("Ohm");
	//	standard_unit	not set for	Impedances
	//	display_unit	not set for	Impedances
	impedances_prop.set_format("%4.2f");
	//	max_value	not set for	Impedances
	//	min_value	not set for	Impedances
	impedances_prop.set_max_alarm("5.0");
	impedances_prop.set_min_alarm("2.8");
	//	max_warning	not set for	Impedances
	//	min_warning	not set for	Impedances
	//	delta_t	not set for	Impedances
	//	delta_val	not set for	Impedances

	impedances->set_default_properties(impedances_prop);
	impedances->set_polling_period(3000);
	impedances->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Impedances does not fire change event
	//	Impedances does not fire archive event
	//	Impedances does not fire data_ready event

	att_list.push_back(impedances);
	
	//	Attribute : SetCurrentsRMS
	SetCurrentsRMSAttrib	*setcurrentsrms = new SetCurrentsRMSAttrib();
	Tango::UserDefaultAttrProp	setcurrentsrms_prop;
	setcurrentsrms_prop.set_description("Statistic when driven by the Libera. One RMS value for every pole\nof the magnet.\nRMS value of the AC setpoint applied on the DAC during the last second.\nX=sqr( (sum(setAC)*sum(setAC)) / n - ((sum(setAC)/n) *(sum(setAC)/n)) )");
	setcurrentsrms_prop.set_label("RMS AC current setpoints/s");
	setcurrentsrms_prop.set_unit("mA");
	//	standard_unit	not set for	SetCurrentsRMS
	//	display_unit	not set for	SetCurrentsRMS
	setcurrentsrms_prop.set_format("%6.3");
	//	max_value	not set for	SetCurrentsRMS
	//	min_value	not set for	SetCurrentsRMS
	//	max_alarm	not set for	SetCurrentsRMS
	//	min_alarm	not set for	SetCurrentsRMS
	//	max_warning	not set for	SetCurrentsRMS
	//	min_warning	not set for	SetCurrentsRMS
	//	delta_t	not set for	SetCurrentsRMS
	//	delta_val	not set for	SetCurrentsRMS

	setcurrentsrms->set_default_properties(setcurrentsrms_prop);
	setcurrentsrms->set_polling_period(0);
	setcurrentsrms->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	SetCurrentsRMS does not fire change event
	//	SetCurrentsRMS does not fire archive event
	//	SetCurrentsRMS does not fire data_ready event

	att_list.push_back(setcurrentsrms);
	
	//	Attribute : SetCurrentsAverage
	SetCurrentsAverageAttrib	*setcurrentsaverage = new SetCurrentsAverageAttrib();
	Tango::UserDefaultAttrProp	setcurrentsaverage_prop;
	setcurrentsaverage_prop.set_description("Statistic when driven by the Libera. One average value for every pole\nof the magnet.\nAverage value of the AC setpoint applied on the DAC during the last second.");
	setcurrentsaverage_prop.set_label("Average AC current setpoints/s");
	setcurrentsaverage_prop.set_unit("mA");
	//	standard_unit	not set for	SetCurrentsAverage
	//	display_unit	not set for	SetCurrentsAverage
	setcurrentsaverage_prop.set_format("%6.3");
	//	max_value	not set for	SetCurrentsAverage
	//	min_value	not set for	SetCurrentsAverage
	//	max_alarm	not set for	SetCurrentsAverage
	//	min_alarm	not set for	SetCurrentsAverage
	//	max_warning	not set for	SetCurrentsAverage
	//	min_warning	not set for	SetCurrentsAverage
	//	delta_t	not set for	SetCurrentsAverage
	//	delta_val	not set for	SetCurrentsAverage

	setcurrentsaverage->set_default_properties(setcurrentsaverage_prop);
	setcurrentsaverage->set_polling_period(0);
	setcurrentsaverage->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	SetCurrentsAverage does not fire change event
	//	SetCurrentsAverage does not fire archive event
	//	SetCurrentsAverage does not fire data_ready event

	att_list.push_back(setcurrentsaverage);
	
	//	Attribute : FramesPerSecond
	FramesPerSecondAttrib	*framespersecond = new FramesPerSecondAttrib();
	Tango::UserDefaultAttrProp	framespersecond_prop;
	framespersecond_prop.set_description("Number of settings applied during the last second");
	framespersecond_prop.set_label("Frames per second");
	//	unit	not set for	FramesPerSecond
	//	standard_unit	not set for	FramesPerSecond
	framespersecond_prop.set_display_unit(" ");
	framespersecond_prop.set_format("%6d");
	//	max_value	not set for	FramesPerSecond
	//	min_value	not set for	FramesPerSecond
	//	max_alarm	not set for	FramesPerSecond
	//	min_alarm	not set for	FramesPerSecond
	//	max_warning	not set for	FramesPerSecond
	//	min_warning	not set for	FramesPerSecond
	//	delta_t	not set for	FramesPerSecond
	//	delta_val	not set for	FramesPerSecond

	framespersecond->set_default_properties(framespersecond_prop);
	framespersecond->set_polling_period(0);
	framespersecond->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	FramesPerSecond does not fire change event
	//	FramesPerSecond does not fire archive event
	//	FramesPerSecond does not fire data_ready event

	att_list.push_back(framespersecond);
	
	//	Attribute : ErrorsPerSecond
	ErrorsPerSecondAttrib	*errorspersecond = new ErrorsPerSecondAttrib();
	Tango::UserDefaultAttrProp	errorspersecond_prop;
	errorspersecond_prop.set_description("Errors detected during the last second");
	errorspersecond_prop.set_label("Errors per second");
	//	unit	not set for	ErrorsPerSecond
	//	standard_unit	not set for	ErrorsPerSecond
	errorspersecond_prop.set_display_unit(" ");
	errorspersecond_prop.set_format("%6d");
	//	max_value	not set for	ErrorsPerSecond
	//	min_value	not set for	ErrorsPerSecond
	//	max_alarm	not set for	ErrorsPerSecond
	//	min_alarm	not set for	ErrorsPerSecond
	//	max_warning	not set for	ErrorsPerSecond
	//	min_warning	not set for	ErrorsPerSecond
	//	delta_t	not set for	ErrorsPerSecond
	//	delta_val	not set for	ErrorsPerSecond

	errorspersecond->set_default_properties(errorspersecond_prop);
	errorspersecond->set_polling_period(0);
	errorspersecond->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	ErrorsPerSecond does not fire change event
	//	ErrorsPerSecond does not fire archive event
	//	ErrorsPerSecond does not fire data_ready event

	att_list.push_back(errorspersecond);
	
	//	Attribute : ErrorCounters
	ErrorCountersAttrib	*errorcounters = new ErrorCountersAttrib();
	Tango::UserDefaultAttrProp	errorcounters_prop;
	errorcounters_prop.set_description("Statistic when driven by the Libera.\nThe total number of errors since the last reset for the \nthree poles.");
	errorcounters_prop.set_label("Error counters");
	errorcounters_prop.set_unit(" ");
	//	standard_unit	not set for	ErrorCounters
	//	display_unit	not set for	ErrorCounters
	errorcounters_prop.set_format("%6d");
	//	max_value	not set for	ErrorCounters
	//	min_value	not set for	ErrorCounters
	//	max_alarm	not set for	ErrorCounters
	//	min_alarm	not set for	ErrorCounters
	//	max_warning	not set for	ErrorCounters
	//	min_warning	not set for	ErrorCounters
	//	delta_t	not set for	ErrorCounters
	//	delta_val	not set for	ErrorCounters

	errorcounters->set_default_properties(errorcounters_prop);
	errorcounters->set_polling_period(0);
	errorcounters->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	ErrorCounters does not fire change event
	//	ErrorCounters does not fire archive event
	//	ErrorCounters does not fire data_ready event

	att_list.push_back(errorcounters);
	
	//	Attribute : Temperatures
	TemperaturesAttrib	*temperatures = new TemperaturesAttrib();
	Tango::UserDefaultAttrProp	temperatures_prop;
	temperatures_prop.set_description("Temperature measurements for the three poles.");
	temperatures_prop.set_label("Temperatures");
	temperatures_prop.set_unit("C");
	//	standard_unit	not set for	Temperatures
	//	display_unit	not set for	Temperatures
	temperatures_prop.set_format("%6.0f");
	//	max_value	not set for	Temperatures
	//	min_value	not set for	Temperatures
	temperatures_prop.set_max_alarm("50");
	//	min_alarm	not set for	Temperatures
	//	max_warning	not set for	Temperatures
	//	min_warning	not set for	Temperatures
	//	delta_t	not set for	Temperatures
	//	delta_val	not set for	Temperatures

	temperatures->set_default_properties(temperatures_prop);
	temperatures->set_polling_period(30000);
	temperatures->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Temperatures does not fire change event
	//	Temperatures does not fire archive event
	//	Temperatures does not fire data_ready event

	att_list.push_back(temperatures);
	

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());

	/*----- PROTECTED REGION ID(Itest2811Controller::Class::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::attribute_factory_after

}



//--------------------------------------------------------
/**
 *	Method      : Itest2811Controller::Itest2811ControllerClass::command_factory()
 *	Description : Create the command object(s)
 *	              and store them in the command list
 */
//--------------------------------------------------------
void Itest2811ControllerClass::command_factory()
{
	/*----- PROTECTED REGION ID(Itest2811Controller::Class::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::command_factory_before


	
	//	Create On command object
	OnClass	*pOnCmd =
		new OnClass("On",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOnCmd);


	
	//	Create Off command object
	OffClass	*pOffCmd =
		new OffClass("Off",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOffCmd);


	
	//	Create Reset command object
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);




	/*----- PROTECTED REGION ID(Itest2811Controller::Class::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::command_factory_after

}




//===================================================================
//	Dynamic attributes related methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void Itest2811ControllerClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;


	/*----- PROTECTED REGION ID(Itest2811Controller::Class::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::create_static_att_list

}


//--------------------------------------------------------
/**
 * method : 		Itest2811ControllerClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void Itest2811ControllerClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Itest2811Controller *dev = static_cast<Itest2811Controller *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()],true);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(Itest2811Controller::Class::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::erase_dynamic_attributes

}



	/*----- PROTECTED REGION ID(Itest2811Controller::Class::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Controller::Class::Additional Methods

} //	namespace
