/*----- PROTECTED REGION ID(Itest2811ChannelStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Itest2811ChannelStateMachine.cpp
//
// description : C++ source for the Itest2811Channel and its alowed
//               methods for commands and attributes
//
// project :     BILT channel interface.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <Itest2811Channel.h>
#include <Itest2811ChannelClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * Itest2811Channel states description:
 *
 * ON :	Magnet is ON, all three channels are ON. 
 * OFF :	Magnet is OFF, all three channels are OFF. 
 * FAULT :	Error detected by the BILT magnet. 
 * ALARM :	Alarm detected on one or more channels. 
 * UNKNOWN :	Communication fault 
 * MOVING :	Waiting for the current slope completion 
 */

namespace Itest2811Channel_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Itest2811Channel::is_CurrentState_allowed()
 *	Description : Execution allowed for Current attribute.
 */
//--------------------------------------------------------

bool Itest2811Channel::is_Current_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
		if (	//	Compare device state with not allowed states for WRITE 
			get_state() == Tango::FAULT	|| 
			get_state() == Tango::UNKNOWN	|| 
			get_state() == Tango::MOVING)
		{
		
	/*----- PROTECTED REGION ID(Itest2811Channel::CurrentStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::CurrentStateAllowed_WRITE

			return false;
		}
		return true;
	}
	else
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::FAULT	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(Itest2811Channel::read_CurrentStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::read_CurrentStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Itest2811Channel::is_VoltageState_allowed()
 *	Description : Execution allowed for Voltage attribute.
 */
//--------------------------------------------------------

bool Itest2811Channel::is_Voltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::FAULT	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(Itest2811Channel::read_VoltageStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::read_VoltageStateAllowed_READ

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Itest2811Channel::is_ImpedanceState_allowed()
 *	Description : Execution allowed for Impedance attribute.
 */
//--------------------------------------------------------

bool Itest2811Channel::is_Impedance_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	if (	//	Compare device state with not allowed states for READ 
		get_state() == Tango::FAULT	|| 
		get_state() == Tango::UNKNOWN)
	{
	
	/*----- PROTECTED REGION ID(Itest2811Channel::read_ImpedanceStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::read_ImpedanceStateAllowed_READ

		return false;
	}
	return true;
}


//=================================================
//	Dynamic Attributes Allowed Methods
//=================================================


	/*----- PROTECTED REGION ID(Itest2811Channel::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================


//--------------------------------------------------------
/**
 *	Method      : Itest2811Channel::is_OnState_allowed()
 *	Description : Execution allowed for On command.
 */
//--------------------------------------------------------

bool Itest2811Channel::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::FAULT	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(Itest2811Channel::OnStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::OnStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Itest2811Channel::is_OffState_allowed()
 *	Description : Execution allowed for Off command.
 */
//--------------------------------------------------------

bool Itest2811Channel::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::FAULT	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(Itest2811Channel::OffStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::OffStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Itest2811Channel::is_ResetState_allowed()
 *	Description : Execution allowed for Reset command.
 */
//--------------------------------------------------------

bool Itest2811Channel::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::FAULT	|| 
		get_state() == Tango::UNKNOWN)
	{

	/*----- PROTECTED REGION ID(Itest2811Channel::ResetStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::ResetStateAllowed

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(Itest2811Channel::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	Itest2811Channel::are_dynamic_commands_allowed

}	// namespace Itest2811Channel_ns
