/*----- PROTECTED REGION ID(Itest::MultiClassesFactory.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        MultiClassesFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible for the creation of
//               all class singleton for a device server. It is called
//               at device server startup.
//
// project :     .
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <tango.h>

//	Add class header files
#include <Itest2811ControllerClass.h>


/**
 *	Create Class singletons and store them in DServer object.
 */

void Tango::DServer::class_factory()
{
	//	Add methods for class init
	add_class(Itest2811Controller_ns::Itest2811ControllerClass::init("Itest2811Controller"));

}

/*----- PROTECTED REGION END -----*/
